name: Node.js CI with Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Copy dist folder to artifact
        run: cp -r dist ${{ github.workspace }}/dist-artifact

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: ${{ github.workspace }}/dist-artifact
